# Generated by Django 3.2.7 on 2021-09-23 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('year', models.DateTimeField()),
                ('cover', models.ImageField(default='deafult_profile_pic.jpeg', upload_to='images/album')),
            ],
        ),
        migrations.CreateModel(
            name='artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('artist_origin', models.TextField()),
                ('photo', models.ImageField(default='deafult_profile_pic.jpeg', upload_to='images/artist')),
            ],
        ),
        migrations.CreateModel(
            name='CMS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('content', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, null=True)),
                ('answer', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='general_settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Parking Bud', max_length=30, null=True)),
                ('company_email', models.EmailField(default='parkingbud@gmail.com', max_length=60, null=True, verbose_name='email')),
                ('company_country_code', models.CharField(default='', max_length=10)),
                ('company_phone_no', models.CharField(blank=True, max_length=20, null=True)),
                ('company_address_line_1', models.CharField(blank=True, max_length=200, null=True)),
                ('company_address_line_2', models.CharField(blank=True, max_length=200, null=True)),
                ('company_country', models.CharField(blank=True, max_length=100, null=True)),
                ('company_city', models.CharField(blank=True, max_length=100, null=True)),
                ('company_state', models.CharField(blank=True, max_length=100, null=True)),
                ('company_zip_code', models.CharField(blank=True, max_length=100, null=True)),
                ('timezone', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='image_settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deafult_profile_pic', models.ImageField(default='deafult_profile_pic.jpeg', help_text='1:1', upload_to='')),
                ('default_parking_spot_pic', models.ImageField(default='provider/images/default_parking_spot_pic.jpg', help_text='2:1', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='SMTP_setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twilio_phone_number', models.CharField(blank=True, default='', max_length=100)),
                ('sendgrid_sender_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='social_media_settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_url', models.CharField(blank=True, default='', max_length=2000)),
                ('facebook_url', models.CharField(blank=True, default='', max_length=2000)),
                ('twitter_url', models.CharField(blank=True, default='', max_length=2000)),
                ('instagram_url', models.CharField(blank=True, default='', max_length=2000)),
                ('linkedin_url', models.CharField(blank=True, default='', max_length=2000)),
                ('youtube_url', models.CharField(blank=True, default='', max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='songs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=400)),
                ('song_mp3', models.FileField(upload_to='images/songs')),
                ('cover', models.ImageField(default='deafult_profile_pic.jpeg', upload_to='images/songs')),
                ('number_of_likes', models.IntegerField()),
                ('likes', models.TextField()),
                ('lyrics', models.CharField(blank=True, default='', max_length=4000)),
                ('genres', models.CharField(blank=True, default='', max_length=400)),
                ('charts', models.CharField(blank=True, default='', max_length=400)),
                ('year', models.DateTimeField()),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='album', to='admins.album')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='artist', to='admins.artist')),
            ],
        ),
        migrations.CreateModel(
            name='playlist_admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('cover', models.ImageField(default='deafult_profile_pic.jpeg', upload_to='images/playlist')),
                ('gener', models.CharField(max_length=400)),
                ('songs', models.ManyToManyField(related_name='admin_playlist', to='admins.songs')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='albums_artist', to='admins.artist'),
        ),
    ]
