# Generated by Django 3.2.7 on 2021-09-23 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('password', models.TextField(default='')),
                ('address_line_1', models.CharField(default='', max_length=200)),
                ('address_line_2', models.CharField(default='', max_length=200)),
                ('profile_pic', models.ImageField(default='deafult_profile_pic.jpeg', upload_to='images/profile')),
                ('otp', models.CharField(default='', max_length=200)),
                ('country_code', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=15)),
                ('country', models.CharField(default='', max_length=100)),
                ('city', models.CharField(default='', max_length=100)),
                ('state', models.CharField(default='', max_length=100)),
                ('zip_code', models.CharField(default='', max_length=100)),
                ('timezone', models.TextField(default='UTC')),
                ('is_user_blocked', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('token', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=60, verbose_name='email')),
                ('full_name', models.CharField(max_length=100)),
                ('country_code', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=15)),
                ('password', models.TextField(default='')),
                ('gender', models.CharField(max_length=15)),
                ('facebook', models.CharField(max_length=2000)),
                ('instagram', models.CharField(max_length=2000)),
                ('bio', models.CharField(max_length=500)),
                ('profile_pic', models.ImageField(default='deafult_profile_pic.jpeg', upload_to='images/profile')),
                ('otp', models.CharField(default='', max_length=200)),
                ('is_user_blocked', models.BooleanField(default=False)),
                ('is_varified', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('token', models.CharField(default='', max_length=10)),
                ('subscription_plan', models.CharField(default='free', max_length=100)),
            ],
        ),
    ]
